apiVersion: v1
kind: Pod
metadata:
  name: test-artifact
spec:
  serviceAccountName: jenkins
  containers:
  - name: test
    image: us-central1-docker.pkg.dev/project-753633bf-7369-418c-920/argocd/jenkinsci:16