pipeline {
    agent any

    environment {
        REGION = "us-central1"
        ZONE = "us-central1-a"
        REPO = "argocd"
        IMAGE = "jenkinsci"
        
    }

    stages {
        stage('Resolve Environment') {
            
    steps {
        script {
            def config = [
                dev: [
                    cluster: "testcluster",
                    namespace: "dev",
                    project: "project-753633bf-7369-418c-920"
                ],
                qa: [
                    cluster: "testcluster",
                    namespace: "dev",
                    project: "project-753633bf-7369-418c-920"
                ],
                uat: [
                    cluster: "testcluster",
                    namespace: "uat",
                    project: "project-753633bf-7369-418c-920"
                ],
                prod: [
                    cluster: "testcluster",
                    namespace: "prod",
                    project: "project-753633bf-7369-418c-920"
                ]
            ]

            if (!config.containsKey(params.ENVIRONMENT)) {
                error "Invalid ENVIRONMENT selected"
            }

            env.CLUSTER_NAME = config[params.ENVIRONMENT].cluster
            env.NAMESPACE    = config[params.ENVIRONMENT].namespace
            env.PROJECTID    = config[params.ENVIRONMENT].project

            echo "Using:"
            echo "Cluster: ${env.CLUSTER_NAME}"
            echo "Namespace: ${env.NAMESPACE}"
            echo "Project: ${env.PROJECTID}"
        }
    }
}

        stage('Show Available Tags') {
            
            steps {
                sh """
                gcloud container clusters get-credentials ${env.CLUSTER_NAME} \
                --zone ${env.ZONE} \
                --project ${env.PROJECTID}
                """
            }
        }
 
        stage('Deploy or rollback') {
            
            steps {
                script{
                def FULLREPO = "${env.REGION}-docker.pkg.dev/${env.PROJECTID}/${env.REPO}/${env.IMAGE}"
                if(params.OPERATION == 'Deploy'){
                echo "🚀 Deploying image: ${params.IMAGE_TAG}"
                sh """
                helm upgrade --install jenkinsci-app ./adminapp \
                --set image.repository=$FULLREPO \
                --set image.tag=${params.IMAGE_TAG} \
                --namespace ${env.NAMESPACE} \
                --create-namespace
                """
                }
                else if(params.OPERATION == 'Rollback'){
                echo "🔁 Rolling back deployment"
                sh """
                helm rollback jenkinsci-app \
                --namespace ${env.NAMESPACE}
                """
            }else {
                error "Invalid OPERATION: ${params.OPERATION}"
            }
            
        }
            }
    }
    


}
    post {
        success {
            echo "✅ Image Deployed successfully to GKE"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}