pipeline {
    agent any

       environment {
        REGION = "us-central1"
        ZONE = "us-central1-a"
        REPO = "argocd"
        IMAGE = "jenkinsci"
        FULLREPO = "${env.REGION}-docker.pkg.dev/${params.PROJECTID}/${env.REPO}/${env.IMAGE}"
    }

    stages {
        stage('Resolve Environment') {
    steps {
        script {
            def config = [
                dev: [
                    cluster: "dev-cluster",
                    namespace: "dev",
                    project: "project-dev"
                ],
                stage: [
                    cluster: "stage-cluster",
                    namespace: "stage",
                    project: "project-stage"
                ],
                prod: [
                    cluster: "prod-cluster",
                    namespace: "prod",
                    project: "project-prod"
                ]
            ]

            if (!config.containsKey(params.ENVIRONMENT)) {
                error "Invalid ENVIRONMENT selected"
            }

            env.CLUSTER_NAME = config[params.ENVIRONMENT].cluster
            env.NAMESPACE    = config[params.ENVIRONMENT].namespace
            env.PROJECTID    = config[params.ENVIRONMENT].project

            echo "Using:"
            echo "Cluster: ${env.CLUSTER_NAME}"
            echo "Namespace: ${env.NAMESPACE}"
            echo "Project: ${env.PROJECTID}"
        }
    }
}

        stage('Show Available Tags') {
            steps {
                sh """
                gcloud container clusters get-credentials ${params.CLUSTER_NAME} \
                --zone ${env.ZONE} \
                --project ${params.PROJECTID}
                """
            }
        }

        stage('Deploy or rollback') {
            
            steps {
                script{
                if(params.OPERATION == 'Deploy'){
                echo "🚀 Deploying image: ${params.IMAGE_TAG}"
                sh """
                helm upgrade --install jenkinsci-app ./adminapp \
                --set image.repository=$FULLREPO \
                --set image.tag=${params.IMAGE_TAG} \
                --namespace ${params.NAMESPACE} \
                --create-namespace
                """
                }
                else if(params.OPERATION == 'Rollback'){
                echo "🔁 Rolling back deployment"
                sh """
                helm rollback jenkinsci-app \
                --namespace ${params.NAMESPACE}
                """
            }else {
                error "Invalid OPERATION: ${params.OPERATION}"
            }
            
        }
            }
    }


}
    post {
        success {
            echo "✅ Image Deployed successfully to GKE"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}