pipeline {
    agent any

       environment {
        REGION = "us-central1"
        ZONE = "us-central1-1"
        REPO = "argocd"
        IMAGE = "jenkinsci"
        FULLREPO = "${env.REGION}-docker.pkg.dev/${params.PROJECTID}/${env.REPO}/${env.IMAGE}"
    }

    stages {

        stage('Show Available Tags') {
            steps {
                sh """
                gcloud container clusters get-credentials ${params.CLUSTER_NAME} \
                --zone ${env.ZONE} \
                --project ${params.PROJECTID}
                """
            }
        }

        stage('Deploy the Image') {
            steps {
                sh """
                helm upgrade --install jenkinsci-app ./adminapp \
                --set image.repository=$FULLREPO \
                --set image.tag=${params.IMAGE_TAG} \
                --namespace ${params.NAMESPACE} \
                --create-namespace
                """
            }
        }
    }

    post {
        success {
            echo "✅ Image Deployed successfully to GKE"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}