pipeline{
    agent  any
    environment {
        PROJECT_ID = "project-753633bf-7369-418c-920"
        REGION = "us-central1"
        REPO = "argocd"
        IMAGE = "jenkinsci"
        FULLREPO = "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}"
        TAG = "${BUILD_NUMBER}"
        }
    stages{
        stage("checkout SCM"){
            steps{
                checkout scm
            }
           
        }
        stage("build DockerImage"){
            steps{
                sh '''
                docker build -t ${IMAGE}:${TAG} .
                '''
            }
        }
        stage("Authenticate to the GCP"){
            steps{
                    sh '''
                    gcloud auth list
                    gcloud auth configure-docker ${REGION}-docker.pkg.dev -q
                    '''
            }
        }
        
                stage('Tag Image') {
            steps {
                sh '''
                docker tag ${IMAGE}:${TAG} ${FULLREPO}:${TAG}
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push ${FULLREPO}:${TAG}
                '''
            }
        }


}
        post {
        success {
            echo "✅ Image pushed successfully to Artifact Registry"
        }
        failure {
            echo "❌ Build failed"
        }
    }
}