name: helm
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    #workflow_dispatch:
    push:
    #     branches:
    #         - release
permissions:
  id-token: write
  contents: read
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
        PROJECT_ID: project-753633bf-7369-418c-920
        REGION: us-central1
        REPO: argocd
        IMAGE: ghaction
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v

      - name: auth with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/79995188627/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-sa@project-753633bf-7369-418c-920.iam.gserviceaccount.com
      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v2
      - name: check gcloud sdk
        run: gcloud version
      - name: confirm identiity
        run: gcloud auth list
      - name: set up helm
        uses: azure/setup-helm@v4
      - name: check helm version
        run: helm version

      - name: configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      - name: create a image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }} .
      - name: push the docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}